stderr: /home/rbarreror/miniconda3/lib/python3.9/site-packages/numpy/core/getlimits.py:542: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
stdout: 2024-02-23 18:06:58,125 - INFO - Start main
2024-02-23 18:06:58,125 - INFO - Reading tables...
stdout: 2024-02-23 18:06:58,128 - INFO - index file read: /home/rbarreror/projects/TurboPutative-web/src/TurboOmicsIntegrator/jobs/123456/EDA/xPreProcessing/index.json
stdout: 2024-02-23 18:06:58,128 - INFO - mdataType file read: /home/rbarreror/projects/TurboPutative-web/src/TurboOmicsIntegrator/jobs/123456/EDA/xPreProcessing/mdataType.json
stdout: 2024-02-23 18:07:00,231 - INFO - Xt file read: /home/rbarreror/projects/TurboPutative-web/src/TurboOmicsIntegrator/jobs/123456/EDA/xPreProcessing/xt.json read
stdout: 2024-02-23 18:07:01,975 - INFO - Xq file read: /home/rbarreror/projects/TurboPutative-web/src/TurboOmicsIntegrator/jobs/123456/EDA/xPreProcessing/xq.json read
stdout: 2024-02-23 18:07:02,774 - INFO - Xm file read: /home/rbarreror/projects/TurboPutative-web/src/TurboOmicsIntegrator/jobs/123456/EDA/xPreProcessing/xm.json read
stdout: 2024-02-23 18:07:02,778 - INFO - mdataType file read: /home/rbarreror/projects/TurboPutative-web/src/TurboOmicsIntegrator/jobs/123456/EDA/xPreProcessing/mdata.json
stdout: 
        #########################################################
        ###           __  __  ____  ______                    ### 
        ###          |  \/  |/ __ \|  ____/\    _             ### 
        ###          | \  / | |  | | |__ /  \ _| |_           ### 
        ###          | |\/| | |  | |  __/ /\ \_   _|          ###
        ###          | |  | | |__| | | / ____ \|_|            ###
        ###          |_|  |_|\____/|_|/_/    \_\              ###
        ###                                                   ### 
        ######################################################### 
       
 
        
stdout: 2024-02-23 18:07:02,781 - INFO - Applying MOFA...
stdout: Groups names not provided, using default naming convention:
- group1, group2, ..., groupG

stderr: Traceback (most recent call last):
  File "/home/rbarreror/projects/TurboPutative-web/src/TurboOmicsIntegrator/scripts/py/mofa_anova_analysis.py", line 220, in <module>
stderr:     main(args)
  File "/home/rbarreror/projects/TurboPutative-web/src/TurboOmicsIntegrator/scripts/py/mofa_anova_analysis.py", line 153, in main
stderr:     projections_df, loadings, explained_variance = apply_mofa(
  File "/home/rbarreror/projects/TurboPutative-web/src/TurboOmicsIntegrator/scripts/py/mofa_anova_analysis.py", line 44, in apply_mofa
stderr:     assert len(tmp) == len(
AssertionError: Duplicated entries found in features_names. Make sure that feature names are not duplicated across different views
stderr:     ent.set_data_matrix(
  File "/home/rbarreror/miniconda3/lib/python3.9/site-packages/mofapy2/run/entry_point.py", line 360, in set_data_matrix
